### ISSUE TITLE
Environment variables not passed to tmux subshell

### ISSUE THREAD

**Issue by herder** [27medkamal/tmux-session-wizard#1]
Hi, thanks for this plugin - a really great idea!

When I'm running it under `zsh` it doesn't get any of the environment variables in the `session-wizard.sh` subshell, causing the call to fail since `fzf` is not present in the PATH.

When I add this check
```bash
if [[ ! "$PATH" == */home/niklas/.fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/niklas/.fzf/bin"
fi

```

it works, but that's obviously not very scalable :)

I haven't found a good way to make sure that all shell variables are passed to the subshell from `tmux` - do you have any ideas on that?

**Comment by 27medkamal** [comment]
I'm using ZSH and I've seen other people use ZSH with this plugin without any problem. Do you maybe have any non-conventional setup? do you have this line in you `~/.zshrc`?
```
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```


And do you have `fzf` in your `/usr/local/bin/fzf`

Those are the places I would check
