### ISSUE TITLE
Option to get a list of windows to choose from does not work

### ISSUE THREAD

**Issue by iraklisg** [27medkamal/tmux-session-wizard#14]
# Steps to follow
1. Install plugin with TPM
```
set -g @plugin '27medkamal/tmux-session-wizard'
```
2) Add the option to my .config/tmux/tmux.conf
```
set -g @session-wizard-windows on # default is off 
```
3) Installed plugin and start a new tmux session

# What to expect
When I press `Cb-T` a popu to appear that lists all windows

# What I get
I get a popup that contains only sessions, similar to what I get with not setting the `@session-wizard-windows on` option

**Comment by 27medkamal** [comment]
I don't usually use this feature, but just tested it, and can confirm it works when sessions other than the current one have more than 1 window. However, I can see that because the current session is filtered out of the fzf results, the windows in the current session which I should probably fix.

Is this the behaviour you're seeing?

**Comment by iraklisg** [comment]
I run 

```bash
tmux new-session -d -s foo -n wina
tmux new-session -d -s bar -n wina
tmux new-window -d -t bar -n winb
tmux attach-session -t foo
```
What I see when I press Cb-T from within session "foo" is: 
![image](https://github.com/user-attachments/assets/6aa526fd-99be-4e19-a7c1-2da4982d44b8)

I would expect to see something like the popup containing "bar:wina bar:winb" to be able to select a particular window
Am I missing something here?

**Comment by 27medkamal** [comment]
I just tested the following after killing my tmux server
```
tmux new-session -d -s foo -n wina
tmux new-session -d -s bar -n wina
tmux new-window -d -t bar -n winb
tmux attach-session -t foo
```
and I can see bar's windows

<img width="221" alt="image" src="https://github.com/user-attachments/assets/d8c44a22-2d32-428f-87e9-ee5ab931dad7">


Are you able to share your `tmux.conf` file? I can have a look further.
Also can you run `tmux show-option -gqv "@session-wizard-windows"` and share the output

Also looping @RensOliemans in who contributed to this feature. Can you confirm if this works for you or not?

**Comment by iraklisg** [comment]
Sure. My tmux config file (no fancy stuff)
```
➜  cat ~/.config/tmux/tmux.conf
setw -g mouse on
setw -g mode-keys vi

# Requires to have xclip installed (apt install xclip)
# Cb-] to enter visual copy mode
# Move with vim keys h,j,k,l
# Start selecting with v
# End selection and copy with y
# Paste with p
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
bind-key p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"

# Tmux Plugin Manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

# Plugin list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin '27medkamal/tmux-session-wizard'

# Plugin config
set -g @catppuccin_flavour 'latte'
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_default_color "#4078c0"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_color "#c9510c"
set -g @catppuccin_status_modules_right "session"
set -g @catppuccin_status_left_separator "█"
set -g @session-wizard 't'
set -g @session-wizard-windows on

# Initialize TMUX plugin manager
run '~/.local/share/tmux/plugins/tpm/tpm'
```
and
```
➜  tmux show-option -gqv "@session-wizard-windows"
on
```

I had previously installed [tmux-sessionx](https://github.com/omerxx/tmux-sessionx). Although I removed it from my tmux plugin list, I hadn't uninstalled it. After [uninstalling it](https://github.com/tmux-plugins/tpm?tab=readme-ov-file#uninstalling-plugins) and running tmux again, I can now see the two windows.
![image](https://github.com/user-attachments/assets/190dc68b-27af-41b5-9a80-2e80c6f1c3c2)

Is it possible that there was some conflict because of that? Please let me further test it and I will report back

**Comment by RensOliemans** [comment]
Thanks for pinging me, but I can't seem to reproduce it. I tried to use your `.tmux.conf` and install `tmux-sessionx` as well, even then I still see the windows. I also can't easily think of a way how `sessionx` might conflict with this plugin.

Something which I can imagine might have happened is the following:
1. You add `set -g @plugin '27medkamal/tmux-session-wizard'` to your `.tmux.conf` and install the plugin with tpm.
2. You run tmux
3. You change the `@session-wizard-windows` setting in `.tmux.conf`, but don't reload the config file.

In which case tmux doesn't know about the `-windows` setting and you would still see only the sessions. After uninstalling sessionx and restarting tmux, tmux will now of course use the new config, 

But that seems at odds with your repro steps above, so tbh I am unsure of how this happened.

Please do some further testing and let us know what you find!

**Comment by iraklisg** [comment]
Strange indeed. I tested in my second PC (please take into account that both PCs are same OS and same dotfiles) and I faced the same issue. I check the value of (`tmux show-option -gqv "@session-wizard-windows" `) and it was on.
Then I manually remove all tmux plugins (rm -rf ~/.local/share/tmux/plugins/*), installed them again and everything works fine. Sorry for not being able to provide more information about that and thank you for your time to respond

**Comment by 27medkamal** [comment]
It's odd indeed, but glad to know it's sorted. Thanks @RensOliemans

**Comment by RensOliemans** [comment]
That is strange, to happen on the second PC as well! I will try and reproduce some more, but am kind of at a loss as to how this can happen.
