### ISSUE TITLE
Multiple keybindings

### ISSUE THREAD

**Issue by catgoose** [27medkamal/tmux-session-wizard#6]
session-wizard.tmux has the comment:

# Multiple bindings can be set. Default binding is "T".

How can I set multiple bindings?

I have tried:

set -g @session-wizard 'C-o'
set -g @session-wizard 'C-o o'

But that just causes TPM to fail.

Thanks!

**Comment by 27medkamal** [comment]
I don't think that would be supported by the current state of the plugin.

If this were to be implemented, one way to do it would be to allow a comma-separated list of key bindings. Happy to accept a pull request if you want to submit one.
