### ISSUE TITLE
Tag inconsistency (nix packaging)

### ISSUE THREAD

**Issue by mandos** [27medkamal/tmux-session-wizard#8]
Hi @27medkamal , 

First of all, great job, I like this plugin a lot and I would like to add this plugin to Nix package ecosystem, but I saw that your tag convention is not consistent (using **v** or **V** prefix). Could you decide what convention you like to use (v prefix maybe) and change other tag?

**Comment by 27medkamal** [comment]
@mandos Thanks for reporting this. I've updated all tags and releases to start with a **V** prefix without removing the existing **v** ones for backwards compatibility. Let me know if that works. Thanks.

**Comment by mandos** [comment]
Thanks @27medkamal, I think this would be enough.
